package com.example.nasa.smart_nepal;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

/**
 * Created by NASA on 3/23/2015.
 */
public class DataBase_Bank {
    public static HashMap<String, List<String>> getInfo()
    {
        HashMap<String, List<String>> BankDetails = new HashMap<String, List<String>>();

        List<String> Everest_Bank = new ArrayList<String>();
        Everest_Bank.add("INSIDE KATHMANDU VALLEY");
        Everest_Bank.add(" Babarmahal Branch, Revenue Office Premise");
        Everest_Bank.add(" Bagbazar Branch, Bagbazar Road");
        Everest_Bank.add(" Balaju Branch, Naya Bazzar");
        Everest_Bank.add(" Bagdole Branch,  Ring Road,Bagdole,Lalitpur");
        Everest_Bank.add(" Bhaktapur , Laxmi Bazzar, Ga:Pali, Suryabinayak ");
        Everest_Bank.add(" Chabahil Branch, Chuchepati");
        Everest_Bank.add(" Durbarmargh , Sherpamall");
        Everest_Bank.add(" Golfutar Branch,Golfutar Shopping Center");
        Everest_Bank.add(" Gongobu Branch,Tokha Entrance");
        Everest_Bank.add(" Gongobu ,Gongobu Chowk");
        Everest_Bank.add(" Gwarko Branch, Gwarko, Lalitpur ");
        Everest_Bank.add(" Jorpati , Micro Bus Stand");
        Everest_Bank.add(" Kalanki ,Near Petrol Pump");
        Everest_Bank.add(" Kalimati Branch, Kalimati Chowk");
        Everest_Bank.add(" Lazimpat Branch, Near Sangrila Hotel");
        Everest_Bank.add(" Machhapokhari , Himalayan City Center");
        Everest_Bank.add(" Maharajgunj, Saleways Dept.Store");
        Everest_Bank.add(" Maitidevi Branch, Near Seto Pul");
        Everest_Bank.add(" Makhan Tole, Near suraj Arcade");
        Everest_Bank.add(" New Baneshwor Branch, Opposite Everest Hotel");
        Everest_Bank.add(" New Road Branch, Khichapokhari");
        Everest_Bank.add(" Old Baneshwor, Old Baneshwor");
        Everest_Bank.add(" Pashupati,  Bajra Ghar,Opp of Brida Asaram");
        Everest_Bank.add(" Putalisadak,  Nepal Share Market Complex");
        Everest_Bank.add(" Singhadurbar,  Singha Durbar Govt. Complex ");
        Everest_Bank.add(" Teku Branch,  Teku Road");
        Everest_Bank.add(" Thamel Branch, A One Business Complex ");
        Everest_Bank.add(" Tokha Road ,Grande International Hospital ");
        Everest_Bank.add(" Tripureshwor , Near Dasarath Stadium ");
        Everest_Bank.add(" Kirtipur Branch, Nayabazzar");
        Everest_Bank.add(" Gwarko Branch,  Gwarko, Lalitpur ");
        Everest_Bank.add(" Lagankhel Branch, Near Buspark ");
        Everest_Bank.add(" Mangalbazzar , Near Café De Patan ");
        Everest_Bank.add(" Pulchowk Branch, Narayani Complex");
        Everest_Bank.add("OUTSIDE KATHMANDU VALLEY");
        Everest_Bank.add(" Baglung Branch,  Aawa Road");
        Everest_Bank.add(" Kohalpur Branch,  Kohalpur");
        Everest_Bank.add(" Nepalgunj, Dhamboji Road");
        Everest_Bank.add(" Chitwan, Chitawan Hospital, Chaubiskoti ");
        Everest_Bank.add(" Narayanghad Branch, Sahidpath, Narayanghad ");
        Everest_Bank.add(" Parsa Bazzar, Khairahani VDC, Parsa Bazar ");
        Everest_Bank.add(" Tulsipur Branch,  B. P. Chowk, Tulsipur ");
        Everest_Bank.add(" Dhading Branch, Nilkantha VDC, Bich Bazar ");
        Everest_Bank.add(" Janakpur Branch, Mills Area, Janakpur ");
        Everest_Bank.add(" Janakpur,  Janaki Mandir Premise ");
        Everest_Bank.add(" Gorkha Branch, Shakti Chowk, Gorkha Bazar ");
        Everest_Bank.add(" Birtamod, Mukti Chowk, Birtamod ");
        Everest_Bank.add(" Damak Branch, Falgunanda Chowk, Damk ");
        Everest_Bank.add(" Attariya Branch, Malakheti VDC, Attariya ");
        Everest_Bank.add(" Dhangadi Branch, Main Road, Dhangadhi ");
        Everest_Bank.add(" Dhangadi, Nepal Khadhay Sasthan, Main Road ");
        Everest_Bank.add(" Tikapur Branch, Khakraula Road, Block No. 13 ");
        Everest_Bank.add(" Chandrauta Branch, Chandrauta, Kapilvastu");
        Everest_Bank.add(" Taulihawa Branch, Taulihawa, Kapilvastu ");
        Everest_Bank.add(" Lekhnath Branch, Taal Chowk, Lekhnath ");
        Everest_Bank.add(" Pokhara Branch, New Road");
        Everest_Bank.add(" Pokhara, Halanchowk, Lakeside ");
        Everest_Bank.add(" Beshisahar Branch,  Besishahar,Lamjung");
        Everest_Bank.add(" Hetauda Branch, Bank Road -10, Hetauda, Makawanpur ");
        Everest_Bank.add(" Biratnagar Branch, Mangaladevi Super Market, Hanuman Das Road");
        Everest_Bank.add(" Parbat Branch, Shahid Chowk,Kushma");



        List<String> NIBL_Bank = new ArrayList<String>();
        NIBL_Bank.add("INSIDE KATHMANDU VALLEY");
        NIBL_Bank.add(" Balkhu, Vayodha Hospital");
        NIBL_Bank.add(" Banepa Branch, Banepa");
        NIBL_Bank.add(" Bhaktapur, At Bhaktapur Durbar Square Main Gate)");
        NIBL_Bank.add(" Battisputali Branch, Battisputali");
        NIBL_Bank.add(" Boudha, At Bhat Bhateni Supermarket Chuchepati");
        NIBL_Bank.add(" Bhatbhateni, At Bhatbhateni Super Market");
        NIBL_Bank.add(" Bhotahity Branch, Bhotahity ");
        NIBL_Bank.add(" Boudha Branch, Boudha-Pipalbot");
        NIBL_Bank.add(" Chhetrapati, At Chhetrapati free clinic");
        NIBL_Bank.add(" DurbargMarg (Head Office)");
        NIBL_Bank.add(" Dhumbarahi Branch, Dhumbarahi");
        NIBL_Bank.add(" Gaushala, Opposite of Police station");
        NIBL_Bank.add(" Gongabu Branch, Gongabu");
        NIBL_Bank.add(" Kamalpokhari, Jain Bhawan,");
        NIBL_Bank.add(" Kalanki Chowk");
        NIBL_Bank.add(" Kalimati Branch,Kalimati ");
        NIBL_Bank.add(" Koteshwor, CT Mall, Kathmandu");
        NIBL_Bank.add(" Kapan, Faika, At Shambala Village Resort");
        NIBL_Bank.add(" Kavre, Dhullikhel, Kathmandu University");
        NIBL_Bank.add(" Lagankhel Branch, Lagankhel");
        NIBL_Bank.add(" Lazimpat Branch, Lazimpat");
        NIBL_Bank.add(" Maharajgunj, At Karnali Hotel,Besides Hot Breads)");
        NIBL_Bank.add(" Maitidevi, At Maitidevi Chowk)");
        NIBL_Bank.add(" Manthali Branch, Manthali, Ramechap  )");
        NIBL_Bank.add(" Metro Police, Ratnapark, Kathmandu");
        NIBL_Bank.add(" Nepal Army, Bhadrakali");
        NIBL_Bank.add(" Nepal Police Training Academy, Maharajgunj");
        NIBL_Bank.add(" Nepal Tourism Board, Pradarshani Marg, Kathmandu");
        NIBL_Bank.add(" New Baneshwor Branch, New Baneshwor");
        NIBL_Bank.add(" Newroad, At Basantapur");
        NIBL_Bank.add(" Newroad, ATM Lounge");
        NIBL_Bank.add(" Pulchowk Branch, Pulchowk");
        NIBL_Bank.add(" Putalisadak Branch, Putalisadak");
        NIBL_Bank.add(" Seepadole Branch, Seepadole");
        NIBL_Bank.add(" SukulDhoka (At Bhaktapur)");
        NIBL_Bank.add(" Thamel, At Best Shopping Centre");
        NIBL_Bank.add(" Thamel Branch, Thamel");
        NIBL_Bank.add(" Thimi,Shankhadhar Shakhwa Chowk");
        NIBL_Bank.add(" Tripureshwor Branch, Tripureshwor");



        NIBL_Bank.add("OUTSIDE KATHMANDU VALLEY");
        NIBL_Bank.add(" Bhairahawa Branch, Bhairahawa");
        NIBL_Bank.add(" Biratnagar Branch, Biratnagar");
        NIBL_Bank.add(" Birgunj Branch, Birgunj");
        NIBL_Bank.add(" Birtamod Branch, Birtamod");
        NIBL_Bank.add(" Butwal Branch, Butwal");
        NIBL_Bank.add(" Pokhara Branch, Chipledhunga, Pokhara");
        NIBL_Bank.add(" Damauli Branch, Damouli");
        NIBL_Bank.add(" Dhangadi Branch, Dhangadi");
        NIBL_Bank.add(" Gaighat Branch, Gaighat");
        NIBL_Bank.add(" Hetauda Branch, Hetauda ");
        NIBL_Bank.add(" Janakpur, At Nepal Rastra Bank,Janakpur");
        NIBL_Bank.add(" Jeetpur Branch, Jeetpur, Bara)");
        NIBL_Bank.add(" Krishnanagar Branch, Krishnanagar");
        NIBL_Bank.add(" Pokhara At Boomerang Restaurant ");
        NIBL_Bank.add(" Lalbandhi Branch, Lalbandhi");
        NIBL_Bank.add(" Narayangadh, Police Training Center");
        NIBL_Bank.add(" Narayangardh Branch, Narayangardh");
        NIBL_Bank.add(" Narayangarh, At International Society of Medical Sciences (ISME, Medical College, Bharatpur)");
        NIBL_Bank.add(" Nepalgunj Branch, Nepalgunj");
        NIBL_Bank.add(" Palpa Branch, Palpa");
        NIBL_Bank.add(" Parsa Branch, Parsa ");
        NIBL_Bank.add(" Surkhet Branch, Surkhet");
        NIBL_Bank.add(" Tulsipur Branch, Tulsipur");
        NIBL_Bank.add(" Waling Branch, Waling");




        List<String> Prabhu_Bank= new ArrayList<String>();
        Prabhu_Bank.add("INSIDE KATHMANDU VALLEY");

        Prabhu_Bank.add(" Badegaun Branch, Thaiba-1, Godawari ,Lalitpur,");
        Prabhu_Bank.add(" Baneshwor Branch ,  Basuki Marg, Old  ");
        Prabhu_Bank.add(" Bhaisepati Branch , Near to Aawash Gate ");
        Prabhu_Bank.add(" Bhaktapur Branch ,  Suryabinayak ");
        Prabhu_Bank.add(" Boudha Branch, Near Boudha Stupa ");
        Prabhu_Bank.add(" Durbarmargh Branch, Annapurna Arcade-1,2nd floor");
        Prabhu_Bank.add(" Gongabu Branch, Near Samakhusi Chwok");
        Prabhu_Bank.add(" Gongabu Branch, Gongabu");
        Prabhu_Bank.add(" Gwarko Branch, Gwarko,lalitpur");
        Prabhu_Bank.add(" Jorpati Branch, Jorpati-3");
        Prabhu_Bank.add(" Kalanki Branch, Next to Sahid Memorial Hospital");
        Prabhu_Bank.add(" Kalimati Branch, Him Basera Building");
        Prabhu_Bank.add(" Kantipath Branch, Opposite of Jyoti Bhawan");
        Prabhu_Bank.add(" Kapan Branch, Kapan");
        Prabhu_Bank.add(" Kausaltar Branch, Kausaltar Chowk");
        Prabhu_Bank.add(" Khichapokhari Branch,  Peoples Plaza");
        Prabhu_Bank.add(" Koteshwor Branch,  Munibhairab Complex");
        Prabhu_Bank.add(" Kumaripati Branch, Near United College");
        Prabhu_Bank.add(" Lainchour Branch, Prabhu Complex");
        Prabhu_Bank.add(" Lalitpur Branch,Jawalakhel Chowk");
        Prabhu_Bank.add(" Lazimpat Branch, Lazimpat");
        Prabhu_Bank.add(" Maharajgunj Branch, Chakrapath,Near Pakistan Embassy");
        Prabhu_Bank.add(" Main Branch, Near Anamnagar,Bhatbateni");
        Prabhu_Bank.add(" Mangalbazar Branch, Krishna Market,Tangal");
        Prabhu_Bank.add(" New Baneshwor Branch, Near Bharosa Hospital");
        Prabhu_Bank.add(" New Road Branch, New Road Gate,Way to Mahabaudha");
        Prabhu_Bank.add(" Satdobato Branch,Way to chapagaun");
        Prabhu_Bank.add(" Sankhamul Branch, Near Sankhamul Bridge");
        Prabhu_Bank.add(" Sinamangal Branch , Side by Kathmandu Medical Collage ");
        Prabhu_Bank.add(" Sukedhara Branch, Near to Sukedhara Police Station");
        Prabhu_Bank.add(" Sundhara Branch, Bagdarbar");
        Prabhu_Bank.add(" Swayambhu Branch, Swayambhu Chowk ");
        Prabhu_Bank.add(" Thamel Branch, Narsingh Chowk");
        Prabhu_Bank.add(" Thimi Branch, Sankhadhar Chowk-13");
        Prabhu_Bank.add("OUTSIDE KATHMANDU VALLEY");

        Prabhu_Bank.add(" Abu Khaireni Branch,Abu Khairaini,tanahu");
        Prabhu_Bank.add(" Amarpath Branch, Amarpath Chowk,Butwal Rupandehi");
        Prabhu_Bank.add(" Bagar Branch,Bagar,Near PN  Campus,Pokhara ,kaski");
        Prabhu_Bank.add(" Baglung Branch,Hallan Chowk,Near Telecom Offfice");
        Prabhu_Bank.add(" Banepa Branch,,Banepa Buspark");
        Prabhu_Bank.add(" Bardaghat Branch,50 meter east from Bardaghat Chowk");
        Prabhu_Bank.add(" Bardibas Branch, Bardibas Mahottari");
        Prabhu_Bank.add(" Battar Branch,Battar Nuwakot");
        Prabhu_Bank.add(" Belbari Branch,New Belbari Bazar,Near police station,Morang");
        Prabhu_Bank.add(" Beni Branch, Beni Municapility 06");
        Prabhu_Bank.add(" Benighat Branch, On the side of Trishuli Bridge via Gorkaha");
        Prabhu_Bank.add(" Besisahar Branch, Besisahar Lamjung");
        Prabhu_Bank.add(" Bhairawaha Branch, Barmeli Tole Bhairawaha");
        Prabhu_Bank.add(" Bharatapur Branch, Inside Narayani Samydayik Hospital Compound");
        Prabhu_Bank.add(" Bhojpur Branch, Bhojpur");
        Prabhu_Bank.add(" Biratnagar Branch,Jaljala Chowk Rangeli Road");
        Prabhu_Bank.add(" Birauta Branch,Birauta Kaski");
        Prabhu_Bank.add(" Birtamode Branch,Kakarivtta Road,East South from Mukti Chowk");
        Prabhu_Bank.add(" Burtibang Branch,Burtibang Bazzar");
        Prabhu_Bank.add(" Butwal Branch, Milan Chowk");
        Prabhu_Bank.add(" Dailekh Branch, Dekendra Chowk");
        Prabhu_Bank.add(" Damak Branch, Damak Municipality-10");
        Prabhu_Bank.add(" Damauli Branch, 100 m south form Damuli Chowk");
        Prabhu_Bank.add(" Darbang Branch, Darbang Branch");
        Prabhu_Bank.add(" Dhangadi Branch,Neelakantha Municipality");
        Prabhu_Bank.add(" Dhangadi Branch, Godawari Road");
        Prabhu_Bank.add(" Dharan Branch, Mehendra Path");
        Prabhu_Bank.add(" Dharke Branch, Naubise VDC");
        Prabhu_Bank.add(" Dolakha Branch, Charikot Bajar");
        Prabhu_Bank.add(" Gadeuli Branch,Piple-7");
        Prabhu_Bank.add(" Gajiri Branch,Gajiri Bazzar");
        Prabhu_Bank.add(" Galkot Branch, Loktantra Chowk");
        Prabhu_Bank.add(" Gaur Branch, Gaur Rautahat");
        Prabhu_Bank.add(" Ghorahi Branch, Damodar Chowk");
        Prabhu_Bank.add(" Gopigunj Branch, Near Jamuniya VDC Building");
        Prabhu_Bank.add(" Gorkha Branch, Bank Road");
        Prabhu_Bank.add(" Guleriya Branch, Near Radhakrishna Chowk");
        Prabhu_Bank.add(" Hariwon Branch, Near Krishna Mandir Chowk");
        Prabhu_Bank.add(" Hetauda Branch, Om Bhawan Kantirajpath");
        Prabhu_Bank.add(" Illam Branch, Illam Municipality");
        Prabhu_Bank.add(" Inaruwa Branch, Inariwa,Sunsari");
        Prabhu_Bank.add(" Itahari Branch, Dharan Road");
        Prabhu_Bank.add(" Jaleshwor Branch, Mahendra Chowk");
        Prabhu_Bank.add(" Janakpur Branch, Bhanu Chowk");
        Prabhu_Bank.add(" Jomsom Branch, Infront of Jomsom Airpot Gate");
        Prabhu_Bank.add(" Kakarvitta Branch, Kakarbhitta");
        Prabhu_Bank.add(" Kalaiya Branch, Hospital road");
        Prabhu_Bank.add(" Kawasoti Branch, Kawasoti Bazzar");
        Prabhu_Bank.add(" Khaireni Branch, Khaireni Chowk");
        Prabhu_Bank.add(" Kohalpur Branch,Kohalpur");
        Prabhu_Bank.add(" Kusma Branch,Kusma Bazzar");
        Prabhu_Bank.add(" Lahan Branch,Opposite of Lahan Police Station");
        Prabhu_Bank.add(" Mahadevbesi Branch,Dharke-3,Near Local BusPark");
        Prabhu_Bank.add(" Mahendranagar Branch, Bhim Datta Municipality");
        Prabhu_Bank.add(" Manigram Branch, Manigram Chowk");
        Prabhu_Bank.add(" Mirchaiya Branch, Katari Chowk");
        Prabhu_Bank.add(" Muktinath Counter Branch, Ranipauwa");
        Prabhu_Bank.add(" Narayanghat Branch,Bharatpur Municipality,main Road");
        Prabhu_Bank.add(" Neejgadh Branch, Neejgadh-8,Bara");
        Prabhu_Bank.add(" Nepalgunj Branch,Surkhet Road,Nepalgunj");
        Prabhu_Bank.add(" Palpa Branch, Makhan Tole");
        Prabhu_Bank.add(" Parasi Branch, Ramgram Municipality,Parasi");
        Prabhu_Bank.add(" Pathari Branch, Loktantra Chowk");
        Prabhu_Bank.add(" Pokhara Branch, Infront Of Padma Narshing Home");
        Prabhu_Bank.add(" Rajbiraj Branch, North of Neta Chowk");
        Prabhu_Bank.add(" Rampur Branch, Near Rampur Agriculture Campus");
        Prabhu_Bank.add(" Sandikharka Branch,Arghakhachi");
        Prabhu_Bank.add(" Sauraha Branch, Bachhauli-02");
        Prabhu_Bank.add(" Simara Branch, Simara,Bara");
        Prabhu_Bank.add(" Siraha Branch, Hemnarayan Chowk");
        Prabhu_Bank.add(" Surkhet Branch, Birendranagar");
        Prabhu_Bank.add(" Tamghas Branch, Tamghas");
        Prabhu_Bank.add(" Tandi Branch, Tandi,Chitwan");
        Prabhu_Bank.add(" Tulsipur Branch, KA line Dang");
        Prabhu_Bank.add(" Walling Branch,Walling Syangja");



        List<String> Standard_Bank = new ArrayList<String>();
        Standard_Bank.add("INSIDE  VALLEY");
        Standard_Bank.add("Kathmandu ");
        Standard_Bank.add("  Lazimpat, Lazimpat Building ");
        Standard_Bank.add("  Maharajgunj , Saleways Deparment Store");
        Standard_Bank.add("  Newroad, Bishal Bazar , Shop No.88 ");
        Standard_Bank.add("  New Baneshwor, Head Office, Opposite to BCC Vawan");
        Standard_Bank.add("  Thamel , Kathmandu Guest House");
        Standard_Bank.add("  Thamel , Hot Bread Chowk, Chaksibari Marg ");

        Standard_Bank.add("Lalitpur ");
        Standard_Bank.add("  Bouddha , Entrance gate of Bouddhanath Stupa ");
        Standard_Bank.add("  Durbar, Marg Hotel De'l Annapurna");
        Standard_Bank.add("  Near UNDP Complex, Lalitpur ");
        Standard_Bank.add("  Teku , Tewa Investment Building ");
        Standard_Bank.add("  UN House, Lalitpur ");

        Standard_Bank.add("OUTSIDE  VALLEY");
        Standard_Bank.add("  Bhairawa, Hotel, Maitri Path Pawan International");
        Standard_Bank.add("  Biratnagar ");
        Standard_Bank.add("  Dharan , B P Koirala Institute Of Health and Science (BPKIHS) premises ");
        Standard_Bank.add("  Pokhara , Lakeside, Hallan Chowk , ATM Lounge, Centre Point ");
        Standard_Bank.add("  Pokhara , Lake Side, Ward No. 6");
        Standard_Bank.add("  Narayanghat");




        List<String> BOK_Bank = new ArrayList<String>();
        BOK_Bank.add("INSIDE KATHMANDU VALLEY");
        BOK_Bank.add(" Bhaktapur, Bhaktapur, Near Rastriya Banijya Bank");
        BOK_Bank.add(" Balaju, Near BID Gate");
        BOK_Bank.add(" Balkhu Chowk toward Kalimati");
        BOK_Bank.add(" Battisputali");
        BOK_Bank.add(" Chabahil, OM Hospital");
        BOK_Bank.add(" Chuchhepati");
        BOK_Bank.add(" Dharmapath, New Road Lounge");
        BOK_Bank.add(" Gongabu, Opposite Of Shiva Temple");
        BOK_Bank.add(" Gyaneshwor, Near German Embessay");
        BOK_Bank.add(" Kamalpokhari, Near Kamalpokhari");
        BOK_Bank.add(" Maharajgunj, Near Pakistan Embassy");
        BOK_Bank.add(" New Baneshwor Chowk, Ahead Of BICC Hall");
        BOK_Bank.add(" New Baneshwor,Baneshwor Lounge");
        BOK_Bank.add(" New Road, Connection Publication House");
        BOK_Bank.add(" Ramshah Path, Near Supreme Court");
        BOK_Bank.add(" Sankhu, Baahal Area");
        BOK_Bank.add(" Sundhara,Civil Mall");
        BOK_Bank.add(" Thamel, Hotel Mandap Resturent and Bar");
        BOK_Bank.add(" Tripureshwor, Side Of Vibor Bikas Bank");
        BOK_Bank.add(" Tripureshwor,Bluebird Mall");
        BOK_Bank.add(" Kavre, Panauti, Near Punyamati Bridge");
        BOK_Bank.add(" Lalitpur, Kumaripati, ATM Lounge");
        BOK_Bank.add(" Lalitpur, Jawalakhel, Near Alka Hospital");
        BOK_Bank.add(" Kamaladi, Opposite Of Pragya Pratisthan");
        
        BOK_Bank.add("OUTSIDE KATHMANDU VALLEY");


        BOK_Bank.add(" Kaski, Pokhara");
        BOK_Bank.add(" Arghakhanchi , Sandhikharka ");
        BOK_Bank.add(" Baglung , Baglung ");
        BOK_Bank.add(" Banke, Kohalpur");
        BOK_Bank.add(" Banke, Nepalgunj");
        BOK_Bank.add(" Bardia, Gulariya");
        BOK_Bank.add(" Chitwan, Narayanghat");
        BOK_Bank.add(" Dadeldhura, Dadeldhura");
        BOK_Bank.add(" Dang,  Tulsipur");
        BOK_Bank.add(" Dang, Ghorai");
        BOK_Bank.add(" Dhanusha, Janakpur");
        BOK_Bank.add(" Gulmi, Tamghas");
        BOK_Bank.add(" Jhapa, Birtamod");
        BOK_Bank.add(" Kailali, Dhangadi");
        BOK_Bank.add(" Kailali, Tikapur");
        BOK_Bank.add(" Kailali, Attariya");
        BOK_Bank.add(" Makwanpur, Hetauda");
        BOK_Bank.add(" Morang, Biratnagar");
        BOK_Bank.add(" Morang, Biratnagar, Nobel Medical College");
        BOK_Bank.add(" Myagdi, Beni");
        BOK_Bank.add(" Nawalparasi, Rajahar");
        BOK_Bank.add(" Parsa, Birgunj");
        BOK_Bank.add(" Rupandehi, Butwal");
        BOK_Bank.add(" Sindhupalchowk, Tatopani");
        BOK_Bank.add(" Siraha, Lahan");
        BOK_Bank.add(" Solukhumbu, Namche");
        BOK_Bank.add(" Sunsari, Dharan");
        BOK_Bank.add(" Sunsari, Itahari");
        BOK_Bank.add(" Surkhet, Surkhet");
        BOK_Bank.add(" Tanahu, Khairenitar");


        List<String> Nabil_Bank = new ArrayList<String>();
        Nabil_Bank.add("INSIDE KATHMANDU VALLEY");
        Nabil_Bank.add(" Anamnagar Near Japan Nepal Energy");
        Nabil_Bank.add(" Banepa, Kavrepalanchowk");
        Nabil_Bank.add(" Bagdarbar,KMC");
        Nabil_Bank.add(" Balaju Branch, Near Himalayan City Centre");
        Nabil_Bank.add(" Bhaktpur Dhurbar Square");
        Nabil_Bank.add("  Bisal Nagar Margh, Bhatbhateni Super Store ");
        Nabil_Bank.add(" Chabahil Branch, Risi Bhakta Margh");
        Nabil_Bank.add(" Dhapashi Branch, Near Sahid Gangalal National Heart Centre ");
        Nabil_Bank.add(" Dhulikhel Branch, Kavrepalanchowk");
        Nabil_Bank.add(" Gwarko, Near Khari Bhot Chowk");
        Nabil_Bank.add(" Halchowk");
        Nabil_Bank.add(" Jorpati, Attarkhel Near Nepal Medical College");
        Nabil_Bank.add(" Jhamshikhel Branch, Near Manbhawan");
        Nabil_Bank.add(" Jorpati, Opposite Of  Hotel Tibet International");
        Nabil_Bank.add(" Kalanki ATM , Near kalanki Chowk");
        Nabil_Bank.add(" Kaushaltar, Near Kaushaltar Bridge");
        Nabil_Bank.add(" Kantipath, Near Fedex Express");
        Nabil_Bank.add(" Kapan, Near Kopan Monastery");
        Nabil_Bank.add(" Kumaripati, ATM Lounge");
        Nabil_Bank.add(" Kamaladi,Nabilhouse");
        Nabil_Bank.add(" Kuleshwor, College Chowk");
        Nabil_Bank.add(" Lalitpur Branch,Near IOE");
        Nabil_Bank.add(" Lazimpat Big Mart");
        Nabil_Bank.add(" Maharajgunj Branch, Opposite Of Embessy Of USA");
        Nabil_Bank.add(" Maitidevi, Near Seto Pool");
        Nabil_Bank.add(" Mangal Bazar, Near Patan Dharbar Square");
        Nabil_Bank.add(" New Road, ATM Lounge");
        Nabil_Bank.add(" New Baneshwor, Ncell, Krishna Tower");
        Nabil_Bank.add(" New Baneshwor, ATM Lounge");
        Nabil_Bank.add(" New Road, Khechapukhu Road");
        Nabil_Bank.add(" Near Road Kathmandu, Kesha Plaza, ");
        Nabil_Bank.add(" Old Baneshwor ATM Lounge");
        Nabil_Bank.add(" Satdobato Branch, Opposite Of Mahendra Adarsha Bidhyashram ");
        Nabil_Bank.add(" Sinamangal Branch, Near Tara Hal Chowk");
        Nabil_Bank.add(" Thamel,  Ambassador garden home ");
        Nabil_Bank.add(" Thamel Branch, Garden Of Dreams");
        Nabil_Bank.add(" Tahachal, Hotel Soaltee");
        Nabil_Bank.add(" Thamel, Narsingh Chowk");
        Nabil_Bank.add(" Thamel Branch, Near Nirvana Garden");
        Nabil_Bank.add(" Thamel, Tom N Jerry Pub");
        Nabil_Bank.add(" Tripureshwore Branch,Near World Trade Center");
        Nabil_Bank.add(" Thamel, Ying Yang Restaurant");

        Nabil_Bank.add("OUTSIDE KATHMANDU VALLEY");
        Nabil_Bank.add(" Attariya, kailali,Kailali VDC Ward NO 7");
        Nabil_Bank.add(" Baglung Branch");
        Nabil_Bank.add(" Besisahar Branch");
        Nabil_Bank.add(" Bhairahawa, Branch, Near Dhurga Mandir");
        Nabil_Bank.add(" Bhalwari,Branch, Near Siddhababa Rice Mill");
        Nabil_Bank.add(" Biratnagar Branch, Near Sanihat Chowk");
        Nabil_Bank.add(" Biratnagar Eye Hospital");
        Nabil_Bank.add(" Birgunj Branch, Adarsha Nagar, Parsa");
        Nabil_Bank.add(" Birgunj, Power House Chowk");
        Nabil_Bank.add(" Birtamod Branch, Hicola Road");
        Nabil_Bank.add(" Butwal Branch, Near Traffic Chowk");
        Nabil_Bank.add(" Chandragadi,Branch");
        Nabil_Bank.add(" Charikot Branch");
        Nabil_Bank.add(" Damak,Branch");
        Nabil_Bank.add(" Dhangadi Branch");
        Nabil_Bank.add(" Dharan Branch, Near Gita Mandir ");
        Nabil_Bank.add(" Ghorahi Branch");
        Nabil_Bank.add(" Gorkha Branch");
        Nabil_Bank.add(" Hetauda");
        Nabil_Bank.add(" Itahari Branch");
        Nabil_Bank.add(" Khandbari Branch");
        Nabil_Bank.add(" Mahendranagar");
        Nabil_Bank.add(" Nepalgunj Branch");
        Nabil_Bank.add(" Pokhara, Halanchowk");
        Nabil_Bank.add(" Pokhara, Lakeside, Hotel MT Kailsah");
        Nabil_Bank.add(" Pokhara, Pokhara Airport");
        Nabil_Bank.add(" Pokhara, Chipledhunga");
        Nabil_Bank.add(" Pokhara, Lakeside Branch");
        Nabil_Bank.add(" Rupandehi, Hotal mamata, ATM Lounge");
        Nabil_Bank.add(" Teendhara Branch, Beena Marg Durbar Marg");
        Nabil_Bank.add(" Tulsipur Branch");


        List<String> Laxmi_Bank = new ArrayList<String>();
        Laxmi_Bank.add("INSIDE KATHMANDU VALLEY");
        Laxmi_Bank.add(" Bansbari, Gangalal Hospital");
        Laxmi_Bank.add(" Bhaktapur, Sallaghari");
        Laxmi_Bank.add(" Bhatbhateni Branch, Near The Asia Foundation");
        Laxmi_Bank.add(" Boudha, Mahakal-6");
        Laxmi_Bank.add(" Durbarmarg, Sherpa Mall Complex");
        Laxmi_Bank.add(" Hattisar, Near Verisk Information Technology");
        Laxmi_Bank.add(" Kamalpokhari, City Centre Mall");
        Laxmi_Bank.add(" Lagankhel, Patan Hospital");
        Laxmi_Bank.add(" Maharajung, Near Bhatbateni Super Market");
        Laxmi_Bank.add(" New Baneshwor, Near Alpha Beta Complex");
        Laxmi_Bank.add(" New Road, Diebold Lounge");
        Laxmi_Bank.add(" Pulchowk, Opp Of Water Induced Disaster Prevention(DWIDP) ");
        Laxmi_Bank.add(" Sukedhara, Near Bigmart");
        Laxmi_Bank.add(" Sundhara, Civil Mall Complex");
        Laxmi_Bank.add(" Swayambhu, Chauni Hospital");
        Laxmi_Bank.add(" Swayambhu, Sanobharang");
        Laxmi_Bank.add(" Teku, Auto Land Building");
        Laxmi_Bank.add(" Thamel, Thamel Chowk, Opp.Hot Breads");
        Laxmi_Bank.add(" Tilganga, Yeti Airlines Complex");
        Laxmi_Bank.add(" Tripureshwor, Ganesh Dal");
        Laxmi_Bank.add("OUTSIDE KATHMANDU VALLEY");
        Laxmi_Bank.add(" Banepa, Kavre, Arniko Highway West");
        Laxmi_Bank.add(" Bhairahawa Branch, Aawha Road");
        Laxmi_Bank.add(" Biratnagar, Tulsi Complex, Main Road");
        Laxmi_Bank.add(" Birgunj, Adarshanagar, Parsa");
        Laxmi_Bank.add(" Birtamod, Anarmani");
        Laxmi_Bank.add(" Butwal Branch, Amar Path");
        Laxmi_Bank.add(" Charikot Branch, Bhimeshwor");
        Laxmi_Bank.add(" Damak, Damak Bazar, Mahendra Highway");
        Laxmi_Bank.add(" Damaquli Branch");
        Laxmi_Bank.add(" Dang, Ghorahi Branch");
        Laxmi_Bank.add(" Dhangadi Branch, Traffic Chauraha");
        Laxmi_Bank.add(" Dhankuta, Hile Branch, Koshi");
        Laxmi_Bank.add(" Dharan Branch, Putali Line");
        Laxmi_Bank.add(" Itahari, Itahari Chowk");
        Laxmi_Bank.add(" Janakpur Branch, Bhanu Chowk");
        Laxmi_Bank.add(" Kohalpur Branch, Near Medical College Road");
        Laxmi_Bank.add(" Narayanghat Branch, Sahid Chowk");
        Laxmi_Bank.add(" Nepalgunj Branch, Surket Road, Near Dhambaugee");
        Laxmi_Bank.add(" Parsa Branch, Khairahani");
        Laxmi_Bank.add(" Pokhara Branch, New Road");
        Laxmi_Bank.add(" Pokhara, Industrial Estate Branch");
        Laxmi_Bank.add(" Pokhara-Lakeside, Barahi Chowk");
        Laxmi_Bank.add(" Salyan, Shreenagar Branch");
        Laxmi_Bank.add(" Syangja, Walling Branch");
        Laxmi_Bank.add(" Taulihawa Branch, Kapilvastu");


        List<String> NB_Bank=new ArrayList<String>();
        NB_Bank.add("INSIDE KATHMANDU VALLEY");
        NB_Bank.add(" Balaju Branch, Near Bisnumati Bridge");
        NB_Bank.add(" Battisputali, Kathmandu, Near Capital Merchant ");
        NB_Bank.add(" Bhainsepati Branch, Bhainsepati Chowk");
        NB_Bank.add(" Bhaktapur Branch, Sallaghari, Near Sallaghari Bus Station");
        NB_Bank.add(" Bhaktapur Cancer Hospital");
        NB_Bank.add(" Bijuli Bazzar Branch,KTM, Near Dhobikhola Bridge");
        NB_Bank.add(" Chhabahil, KL Tower");
        NB_Bank.add(" Jamal, United ATM Lounge");
        NB_Bank.add(" Jorpati Branch, Near Jorpati Chowk");
        NB_Bank.add(" Kalimati Branch, Kalimati Chowk ");
        NB_Bank.add(" Kamaladi Corporate Office, Infront Of Trichandra Campus");
        NB_Bank.add(" Kamalpokhari, Jain Mandir");
        NB_Bank.add(" Kapan Branch, Near Ganesh Temple");
        NB_Bank.add(" Kumaripati Branch, Neat Mahayan Petrol Pump");
        NB_Bank.add(" Lazimpat,, Bigmart Super Market");
        NB_Bank.add(" New Road Branch, Opposite Of Pasupati Plaza");
        NB_Bank.add(" Putalisadak, Kathmandu Plaza Building");

        NB_Bank.add("OUTSIDE KATHMANDU VALLEY");

        NB_Bank.add(" Battar Branch, Near Batter Station");
        NB_Bank.add(" Bhairahawa Branch");
        NB_Bank.add(" Bhojpur Branch");
        NB_Bank.add(" Biratnagar Branch, Dhadiram Market");
        NB_Bank.add(" Birgunj Branch, Hotel Makalu Building");
        NB_Bank.add(" Butwal Branch, Traffic Chowk");
        NB_Bank.add(" Dhangadi Branch, Chahuraha, Main Road");
        NB_Bank.add(" Dharan Branch");
        NB_Bank.add(" Hetauda, Main Road");
        NB_Bank.add(" Janakpur Branch");
        NB_Bank.add(" Narayangarh Branch");
        NB_Bank.add(" Nepalgunj Branch, Dhamboji");
        NB_Bank.add(" Nuwakot, Trisuli");
        NB_Bank.add(" Pokhara Branch. B P Marg");
        NB_Bank.add(" Pokhara, Pokhara Nursing Campus");
        NB_Bank.add(" Rasuwa, Dhunche");


       List<String> RB_Bank = new ArrayList<String>();
        RB_Bank.add("INSIDE KATHMANDU VALLEY");
        RB_Bank.add(" Balaju Chowk");
        RB_Bank.add(" Bir Hospital, Ratna Park");
        RB_Bank.add(" Bhotahity, Near Ratna Park");
        RB_Bank.add(" Bhudhanilkantha, Near Bhudhanilkantha Temple");
        RB_Bank.add(" Dharmapath, ATM  Lounge");
        RB_Bank.add(" Gaushala");
        RB_Bank.add(" Kalanki branch, Near Kalanki Chowk");
        RB_Bank.add(" Kirtipur Branch, Opposite Of Ganesh Mandir");
        RB_Bank.add(" Lagankhel, Near Lalitpur District Court");
        RB_Bank.add(" Maitedevi Branch Office,Near New Summit School");
        RB_Bank.add(" Narayan Gopal Chowk, Maharajgunj");
        RB_Bank.add(" New Baneshwor ,Near Nepal Oil Corporation");
        RB_Bank.add(" Nepal Airline Corporation, Near New Road Gate");
        RB_Bank.add(" Naxal, Inside Nepal Police Headquaters");
        RB_Bank.add(" New Road, Bishal Bazar");
        RB_Bank.add(" Pulchowk, Behind Everest Bank");
        RB_Bank.add(" Sanothimi, HSEB Area");
        RB_Bank.add(" Surya Binayak, Surya Binayak Oil Store");
        RB_Bank.add(" Tribhuvan International Airport Branch Office");
        RB_Bank.add(" Teku Branch, Bhansar Margh");
        RB_Bank.add(" Thamel, Tridevi Margh");
        RB_Bank.add(" Singhadurbar, Near NTC Office");

        RB_Bank.add("OUTSIDE KATHMANDU VALLEY");
        RB_Bank.add(" Atariya");
        RB_Bank.add(" Baitadi");
        RB_Bank.add(" Bardaghat");
        RB_Bank.add(" Bargachhi");
        RB_Bank.add(" Belbari");
        RB_Bank.add(" Bhadrapur");
        RB_Bank.add(" Bhairahawa");
        RB_Bank.add(" Bharatpur");
        RB_Bank.add(" Biratnagar");
        RB_Bank.add(" Birgunj");
        RB_Bank.add(" Birtamod");
        RB_Bank.add(" Butwal");
        RB_Bank.add(" Dadeldhura");
        RB_Bank.add(" Damak");
        RB_Bank.add(" Dhading");
        RB_Bank.add(" Dhangadi");
        RB_Bank.add(" Dharan");
        RB_Bank.add(" Dhulikhel");
        RB_Bank.add(" Gaighat");
        RB_Bank.add(" Gajuri");
        RB_Bank.add(" Garudabazar");
        RB_Bank.add(" Gaur");
        RB_Bank.add(" Gorkha");
        RB_Bank.add(" Gulariya");
        RB_Bank.add(" Gulmi");
        RB_Bank.add(" Hetauda");
        RB_Bank.add(" Inaruwa");
        RB_Bank.add(" Itahari");
        RB_Bank.add(" Jalesor");
        RB_Bank.add(" Janakpur");
        RB_Bank.add(" Kalaiya");
        RB_Bank.add(" Kawasoti");
        RB_Bank.add(" Kohalpur");
        RB_Bank.add(" Kusma");
        RB_Bank.add(" Lahan");
        RB_Bank.add(" Lalbandi");
        RB_Bank.add(" Mahendranagar");
        RB_Bank.add(" Mirchaiya");
        RB_Bank.add(" Narayanghat");
        RB_Bank.add(" Nepalgunj");
        RB_Bank.add(" Nijgadh");
        RB_Bank.add(" Palpa");
        RB_Bank.add(" Parasi");
        RB_Bank.add(" Pokhara,Prithvichowk");
        RB_Bank.add(" Pokhara, Amar Singh Chowk");
        RB_Bank.add(" Pokhara, Mahendrapul");
        RB_Bank.add(" Rajbiraj");
        RB_Bank.add(" Ramnagar Bajar");
        RB_Bank.add(" Sandikharka");
        RB_Bank.add(" Shreepur");
        RB_Bank.add(" Sindhuli");
        RB_Bank.add(" Siraha");
        RB_Bank.add(" Surkhet");
        RB_Bank.add(" Taulihawa");
        RB_Bank.add(" Tulsipur");
        RB_Bank.add(" Urlabari");

        List<String> SBI_Bank = new ArrayList<String>();
        SBI_Bank.add("INSIDE KATHMANDU VALLEY");

        SBI_Bank.add(" Bhaisepati, Opposite Of Bisnu Shopping Centre");
        SBI_Bank.add(" Bhaktapur, Near Prabhu bank");
        SBI_Bank.add(" Babarmahal, Babarmahal Chowk");
        SBI_Bank.add(" Boudha, Near Bhatbhateni Super Market");
        SBI_Bank.add(" Dallu");
        SBI_Bank.add(" Durbar Marg Main Branch");
        SBI_Bank.add(" Gaushala");
        SBI_Bank.add(" Gongabu");
        SBI_Bank.add(" Gwarko, Near Mahalaxmi Hardware");
        SBI_Bank.add(" Kalanki, Near Makalu Petrol Pump");
        SBI_Bank.add(" Maharajgunj, Bha Bhateni Super Market Ring Road");
        SBI_Bank.add(" New Baneshwor,Opposite Of Shantinagar Gate, Near Merojob.com");
        SBI_Bank.add(" New Road, Dharmapath");
        SBI_Bank.add(" Old Baneshwor,Sinamangal Road");
        SBI_Bank.add(" Patan, Jawalakhel, Near Jawalkhel Chowk");
        SBI_Bank.add(" Teku, Kuleshwor Margh About 100m From Balkhu Chowl ");
        SBI_Bank.add(" Thamel, Thabai Road, ");
        SBI_Bank.add(" Tripureshwor, Tripura Margh, Opposite To BOK");
        SBI_Bank.add(" Lazimpat, Embassy of India Ext. Counter");
        SBI_Bank.add(" Pashupati,  Pashupatinath Ext. Counter");
        SBI_Bank.add(" Lazimpat, Indian Visa Service Centre");
        SBI_Bank.add(" Kathmandu, Regional Office");
        SBI_Bank.add(" Hattisar,  Corporate Office ");

        SBI_Bank.add("OUTSIDE KATHMANDU VALLEY");

        SBI_Bank.add(" Abu Khaireni");
        SBI_Bank.add(" Birgunj");
        SBI_Bank.add(" Damauli");
        SBI_Bank.add(" Dhangadi");
        SBI_Bank.add(" Hetauda");
        SBI_Bank.add(" Janakpur");
        SBI_Bank.add(" Rampur");
        SBI_Bank.add(" Ratnanagar");
        SBI_Bank.add(" Birgunj, CGI Ext. Counter");
        SBI_Bank.add(" Besisahar");
        SBI_Bank.add(" Baglung");
        SBI_Bank.add(" Bhairahawa");
        SBI_Bank.add(" Butwal");
        SBI_Bank.add(" Gulmi");
        SBI_Bank.add(" Palpa");
        SBI_Bank.add(" Parasi");
        SBI_Bank.add(" Pokhara");
        SBI_Bank.add(" Sandhikharka");
        SBI_Bank.add(" Shishuwa");
        SBI_Bank.add(" Srijana Chowk");
        SBI_Bank.add(" Waling");
        SBI_Bank.add(" Pokhara, Pension Paying Office");
        SBI_Bank.add(" Dang");
        SBI_Bank.add(" Narayangarh");
        SBI_Bank.add(" Nepalgunj");
        SBI_Bank.add(" Surkhet");
        SBI_Bank.add(" Nepalgunj, Regional Office");
        SBI_Bank.add(" Mahendra Nagar");
        SBI_Bank.add(" Tikapur");



        List<String> Himalayan_Bank = new ArrayList<String>();
        Himalayan_Bank.add("INSIDE KATHMANDU VALLEY");

        Himalayan_Bank.add(" Ason Chowk");
        Himalayan_Bank.add(" Battisputali, Near Golden Gate College");
        Himalayan_Bank.add(" Bhaktapur,  Sukuldhoka,");
        Himalayan_Bank.add(" Bhaktapur, Dudhpati, Birendra Sainik School");
        Himalayan_Bank.add(" Boudha,  Bhatbhateni Supermarket");
        Himalayan_Bank.add(" BabarMahal Re-visited");
        Himalayan_Bank.add(" Bhaktapur Branch");
        Himalayan_Bank.add(" Chabahil Branch");
        Himalayan_Bank.add(" Chhetrapati Hospital");
        Himalayan_Bank.add(" DilliBazaar Branch, Near Binaya Medical Hall");
        Himalayan_Bank.add(" Durbarmarg, Kathmandu (Hotel Annapurna)");
        Himalayan_Bank.add(" Dillibazaar.  Siddhi Poly Clinic");
        Himalayan_Bank.add(" Halchowk, Sasastra Prahari (Army Police) ");
        Himalayan_Bank.add(" Jhamsikhel,  Near 8 Degree");
        Himalayan_Bank.add(" Jamal Chowk");
        Himalayan_Bank.add(" Jawalakhel, St. Xaviers School");
        Himalayan_Bank.add(" Koteshwor, Bhatbhateni Supermarket");
        Himalayan_Bank.add(" Kaushaltar Branch");
        Himalayan_Bank.add(" Kalanki Branch, Near Tax Office");
        Himalayan_Bank.add(" Kamaladi, Corporate Office, Side of Pragya Pratisthan");
        Himalayan_Bank.add(" Maharajgunj Branch, Near TU Teaching Hospital");
        Himalayan_Bank.add(" Mangalbazaar, Gabahal");
        Himalayan_Bank.add(" Maharajgunj,  Bhatbhateni Supermarket");
        Himalayan_Bank.add(" Maharajgunj, T.U Teaching Hospital"); Himalayan_Bank.add("Maitidevi, Near Bijaya Smarak School "); Himalayan_Bank.add("Makhan, Suraj Arcade ATM Lounge");
        Himalayan_Bank.add(" New Baneshwor Branch");
        Himalayan_Bank.add(" Nagarkot, Near Sainik Awasiya Mahavidyalya");
        Himalayan_Bank.add(" New Road, New Road Gate");
        Himalayan_Bank.add(" New Road Branch, Near Bishal Bazar");
        Himalayan_Bank.add(" New Baneshwor, ILFC Building");
        Himalayan_Bank.add(" Putalisadak, New Plaza");
        Himalayan_Bank.add(" Patan Branch, Mahaphal Road");
        Himalayan_Bank.add(" Sorahkhutte Branch");
        Himalayan_Bank.add(" Samakhushi Branch");
        Himalayan_Bank.add(" Satdobato Branch, Near Satdobato Chowk");
        Himalayan_Bank.add(" Thapathali, Blue Bird Mall");
        Himalayan_Bank.add(" Tangal, Bhatbhateni Supermarket");
        Himalayan_Bank.add(" Tripureshwor, United Trade Center");
        Himalayan_Bank.add(" Thamel, Hotel Manang");
        Himalayan_Bank.add(" Teku Branch");
        Himalayan_Bank.add(" Thamel (Sagarmatha Complex)");
        Himalayan_Bank.add(" Thamel, Chaksibari");
        Himalayan_Bank.add(" Thamel Branch (In Front Of Tridevi Temple)");
        Himalayan_Bank.add(" Thamel Branch Premise");

        Himalayan_Bank.add("OUTSIDE KATHMANDU VALLEY");

        Himalayan_Bank.add(" Birgunj Branch ");
        Himalayan_Bank.add(" Bhartpur Branch");
        Himalayan_Bank.add(" Birtamod Branch");
        Himalayan_Bank.add(" Biratnagar Branch");
        Himalayan_Bank.add(" Butwal Branch");
        Himalayan_Bank.add(" Banepa Branch");
        Himalayan_Bank.add(" Bhairahawa Branch");
        Himalayan_Bank.add(" Damak Branch");
        Himalayan_Bank.add(" Dhading Branch");
        Himalayan_Bank.add(" Hetauda Branch");
        Himalayan_Bank.add(" Dharan Branch");
        Himalayan_Bank.add(" Ghorahi Branch");
        Himalayan_Bank.add(" Narayanghad, Chitwan Medical College");
        Himalayan_Bank.add(" Nepalgunj Branch");
        Himalayan_Bank.add(" Itahari Branch");
        Himalayan_Bank.add(" Trisuli Branch");
        Himalayan_Bank.add(" Baglung Branch");
        Himalayan_Bank.add(" Parsa Branch");
        Himalayan_Bank.add(" Palpa Branch");
        Himalayan_Bank.add(" Pokhara Branch");
        Himalayan_Bank.add(" Pokhara. Hotel Meera, Lakeside ");
        Himalayan_Bank.add(" Tandi, Sauraha");
        Himalayan_Bank.add(" Tandi Branch");


        List<String> Megha_Bank = new ArrayList<String>();

        Megha_Bank.add("INSIDE KATHMANDU VALLEY");
        Megha_Bank.add(" Bouddha, Near Bouddha Stupa");
        Megha_Bank.add(" Bhaktapur,Timi, Near Sanothimi Campus");
        Megha_Bank.add(" Jawalakhel, Opposite Of Nepal Administrative Staff College");
        Megha_Bank.add(" Kapan, Near Gopi Krishna Hall");
        Megha_Bank.add(" Kantipath, Corporate Office, Opposite Of Election Commission");
        Megha_Bank.add(" Maharajgunj , Maharajgunj Chowk");
        Megha_Bank.add(" Maitidevi, Near Rastriya Banijya Bank");
        Megha_Bank.add(" New Baneshwor, Opposite Of BICC Hall ");
        Megha_Bank.add(" New Road, Near E-spot");
        Megha_Bank.add(" Naxal, Naxal Chowk");
        Megha_Bank.add(" Teku, Malla Complex");
        Megha_Bank.add(" Thamel, Ammrit Marg");
        Megha_Bank.add("OUTSIDE KATHMANDU VALLEY");
        Megha_Bank.add(" Arghakhanchi, Near Milan Chowk");
        Megha_Bank.add(" Butwal, Near Ram Mandir");
        Megha_Bank.add(" Bhairahawa, Bermali Tole Chowk");
        Megha_Bank.add(" Birtamod, Mukti Chowk");
        Megha_Bank.add(" Birgunj, Neena Commercial Complex");
        Megha_Bank.add(" Biratnagar, Opposite Of Life Guard Hospital");
        Megha_Bank.add(" Chautara, Sindhupalchowk, Opposite Of District Forest House");
        Megha_Bank.add(" Dailekh, Debkota Chowk");
        Megha_Bank.add(" Dhangadi, Main Dhangadi Bazar");
        Megha_Bank.add(" Dhading, Bizbazar Chowk");
        Megha_Bank.add(" Dharan, Bhanu Chowk");
        Megha_Bank.add(" Ghorahi, Tulsipur Chowk");
        Megha_Bank.add(" Janakpur, Dhanusha");
        Megha_Bank.add(" Sarlahi, Hariwan,  Near Kadariya Chowk");
        Megha_Bank.add(" Narayanghat, Pulchowk");
        Megha_Bank.add(" Nepalgunj, Pushpalal Chowk");
        Megha_Bank.add(" Pokhara, New Road, Near Sabhagriha Chowk");
        Megha_Bank.add(" Syafru Besi, Rasuwa");

        List<String> GlobalIME_Bank = new ArrayList<String>();
        GlobalIME_Bank.add("INSIDE KATHMANDU VALLEY");
        GlobalIME_Bank.add(" Airport, TIA Domestic Terminal");
        GlobalIME_Bank.add(" Anamnagar Branch, Near Japan Nepal Clean Energy");
        GlobalIME_Bank.add(" Ason Chowk");
        GlobalIME_Bank.add(" Balkhu, Office Of The Controller Of Examination");
        GlobalIME_Bank.add(" Banasthali ATM, Near Banasthali School");
        GlobalIME_Bank.add(" Baneshwor, White House Complex, Midbaneshwor");
        GlobalIME_Bank.add(" Bouddha ATM Lounge");
        GlobalIME_Bank.add(" Bouddha ATM, Moktal Plaza, Bouddha");
        GlobalIME_Bank.add(" Chabahil ATM Lounge,Opp. To Medicare Hospital");
        GlobalIME_Bank.add(" Chhetrapati ATM, Hotal Harati Building");
        GlobalIME_Bank.add(" Dhapasi ATM, Basundhara Chowk");
        GlobalIME_Bank.add(" Dillibazar, Pipalbot Ukalo");
        GlobalIME_Bank.add(" Gongabhu,Gongabu Branch");
        GlobalIME_Bank.add(" Gyaneshwor ATM,Sano Gaucharan");
        GlobalIME_Bank.add(" Jamal, Nachghar Shopping Complex ");
        GlobalIME_Bank.add(" Kalanki Branch, In Ganesh Man Singh Path");
        GlobalIME_Bank.add(" Kamaladi Branch, Behind Pragya Pratisthan");
        GlobalIME_Bank.add(" Kantipath, ATM Lounge");
        GlobalIME_Bank.add(" Kirtipur ATM, Tribhuvan University");
        GlobalIME_Bank.add(" Koteshwor Chowk, Koteshwor Branch");
        GlobalIME_Bank.add(" Kuleshwor ATM MM Building Nayabasti");
        GlobalIME_Bank.add(" Kupondole, Kandevsthal");
        GlobalIME_Bank.add(" Lagankhel, Lagankhel Buspark");
        GlobalIME_Bank.add(" Maharajgunj, Bhatbateni Super Market");
        GlobalIME_Bank.add(" Mangal Bazar ATM");
        GlobalIME_Bank.add(" Naxal Branch");
        GlobalIME_Bank.add(" Naxal, Police Headquater");
        GlobalIME_Bank.add(" New Road, New Road Branch");
        GlobalIME_Bank.add(" Panipokharai, IME Complex");
        GlobalIME_Bank.add(" Pepsicola, Suncity Apartment");
        GlobalIME_Bank.add(" Pulchowk Branch, Dhamkal Mod");
        GlobalIME_Bank.add(" Putalisadak, IME Centre");
        GlobalIME_Bank.add(" Satdobato Branch, Tikabhairab Sadak");
        GlobalIME_Bank.add(" Satungal, Armed Police Force Hospital");
        GlobalIME_Bank.add(" Singha Durbar, Baggikhana");
        GlobalIME_Bank.add(" Sundhara, Sundhara Branch");
        GlobalIME_Bank.add(" Suryabinak Branch, Near Lumbini Bank Limited");
        GlobalIME_Bank.add(" Thamel Lounge,Thamel Branch");
        GlobalIME_Bank.add(" Thamel, Near Nursing Chowk");
        GlobalIME_Bank.add(" Tripureshwor, Mayaram Bholaram Petrol Pump");
        GlobalIME_Bank.add("OUTSIDE KATHMANDU VALLEY");
        GlobalIME_Bank.add(" Baglung, Loktantrik Chowk");
        GlobalIME_Bank.add(" Baitadi, Gothalapani");
        GlobalIME_Bank.add(" Bhairawaha, Narayansthan");
        GlobalIME_Bank.add(" Biratnagar, Koshi Zonal Hospital");
        GlobalIME_Bank.add(" Biratnagar, Main Road");
        GlobalIME_Bank.add(" Biratnagar, Raghupati Jute Mill ATM");
        GlobalIME_Bank.add(" Birgunj, Adarshanagar, Hotel Makalu");
        GlobalIME_Bank.add(" Butwal, Ram Mandir Line");
        GlobalIME_Bank.add(" Chitwan, Tandi, Sauraha Chowk");
        GlobalIME_Bank.add(" Dadeldhura, Bagbazar");
        GlobalIME_Bank.add(" Dhading, Baireni Branch");
        GlobalIME_Bank.add(" Dhangadi, Main Road, Chauraha");
        GlobalIME_Bank.add(" Ghorahi,Dang");
        GlobalIME_Bank.add(" Gulmi, Tamghas, Putali Bazar");
        GlobalIME_Bank.add(" Hetauda, Kanti Rajpath Ward No.3");
        GlobalIME_Bank.add(" Illam, Phikkal Chowk");
        GlobalIME_Bank.add(" Itahari, Fulbari Bazar");
        GlobalIME_Bank.add(" Janakpur, Dhanusha");
        GlobalIME_Bank.add(" Jhapa, Birtamode");
        GlobalIME_Bank.add(" Jhapa, Charali Branch");
        GlobalIME_Bank.add(" Jhapa, Dhulabari Bazar");
        GlobalIME_Bank.add(" Kailali, Lamki Bazar");
        GlobalIME_Bank.add(" Kapilvastu, Jeetpur Branch");
        GlobalIME_Bank.add(" Kawasoti Branch");
        GlobalIME_Bank.add(" Kusma, Dhaneshwor Chowk");
        GlobalIME_Bank.add(" Lahan, Main Road");
        GlobalIME_Bank.add(" Mahendranagar, 2 No. Galli");
        GlobalIME_Bank.add(" Myagdi, Beni, New Road");
        GlobalIME_Bank.add(" Ntarayanghat, Shahid Chowk");
        GlobalIME_Bank.add(" Nepalgunj, Pushpalal Chowk");
        GlobalIME_Bank.add(" Nepalgunj, Tribhuwanchowk");
        GlobalIME_Bank.add(" Pokhara, Lakeside ATM Lounge");
        GlobalIME_Bank.add(" Pokhara, Lakeside, Near Thik Thak Restaurant");
        GlobalIME_Bank.add(" Pokhara, Lakeside, Prime ATM Lounge");
        GlobalIME_Bank.add(" Pokhara, New Road");
        GlobalIME_Bank.add(" Pokhara, Prithvi Chowk");
        GlobalIME_Bank.add(" Rajbiraj Branch");
        GlobalIME_Bank.add(" Sarlahi, Lalbandi-01");
        GlobalIME_Bank.add(" Siraha Branch");
        GlobalIME_Bank.add(" Siraha, Mirchaiya Branch");
        GlobalIME_Bank.add(" Sunsari, Dharan");
        GlobalIME_Bank.add(" Surkhet, Birendra Nagar, Birendra Chowk");
        GlobalIME_Bank.add(" Tulsipur, Tulsipur Counter");
        GlobalIME_Bank.add(" Udayapur, Gaighat,Shanti Nagar");
        
        List<String> Machapuchre_Bank = new ArrayList<String>();
        Machapuchre_Bank.add("INSIDE KATHMANDU VALLEY");
        Machapuchre_Bank.add(" Aside Samai Dental College, chabahil");
        Machapuchre_Bank.add(" Samakhusi Chowk,Kathmandu");
        Machapuchre_Bank.add(" Nepal Rastraya Bank’s gate ,Baluwatar,");
        Machapuchre_Bank.add(" Kathmandu Mall,New Road,Kathmandu Nepal");
        Machapuchre_Bank.add(" New Road");
        Machapuchre_Bank.add(" Singa Durbar Primises");
        Machapuchre_Bank.add(" Nepal Electricity Authority Primeises, Ratnapark");
        Machapuchre_Bank.add(" Mangal Bazzar, lalitpur ");
        Machapuchre_Bank.add(" Putalisadak");
        Machapuchre_Bank.add(" Nepal Rastraya Bank Gate ,Thapathali");
        Machapuchre_Bank.add(" Kathmandu Metropolitian City-15,Swayambhu chwok");
        Machapuchre_Bank.add(" Sano Thimi,Bhaktapur");
        Machapuchre_Bank.add(" Boudha Atm,Boudha Branch,Kathmandu");
        Machapuchre_Bank.add(" Pepsicola Chowk, Purano Sinamangal-35");
        Machapuchre_Bank.add(" Pyangaun Bus Park,Chapagaun-6");
        Machapuchre_Bank.add(" MBL Tower,Lazimpat, Kathmandu");
        Machapuchre_Bank.add(" Hot Breads Chowk,Thamel");
        Machapuchre_Bank.add(" New Road Gate,Kathmandu ,Nepal ");
        Machapuchre_Bank.add(" CIAA premises,Bhatbhateni,Kathmandu, Nepal");
        Machapuchre_Bank.add(" Gwarko, Lalitpur,015203333,015201169");

        Machapuchre_Bank.add("OUTSIDE KATHMANDU VALLEY");

        Machapuchre_Bank.add(" Mhendranagar-1, Sakhuwa,Nepal ");
        Machapuchre_Bank.add(" JanakChawak,Ram Mandir,Dhanusha");
        Machapuchre_Bank.add(" Katri Chowk,Mirchaiya,Siraha,Nepal");
        Machapuchre_Bank.add(" Nepal Rastraya Bank Premises ,Pardi ,Pokhara ");
        Machapuchre_Bank.add(" S.R Complex,Devkota Chowk,Ward no.12,Siddharanagar Municipality");
        Machapuchre_Bank.add(" Bagar ,Pokhara,Tel:+97761541226");
        Machapuchre_Bank.add(" Puthang Airport,Marpah,Ward no.5,Tel:+97769440098");
        Machapuchre_Bank.add(" Illam,Tel:+97727521710 ");
        Machapuchre_Bank.add(" Link Road,Ghantagar,Tel:+97751524828 ");
        Machapuchre_Bank.add(" Nepal Rastraya Bank Gate,Dhampojhi-1,Nepalgung");
        Machapuchre_Bank.add(" Bhadrapur Road,Birtamod,Tel:+97723541600");
        Machapuchre_Bank.add(" Dharan Road,Ithari");
        Machapuchre_Bank.add(" Vyas Municipality-10,Mahersichowk,Tanahu,Tel:+97765560500 ");
        Machapuchre_Bank.add(" Highway Line,Damauli");
        Machapuchre_Bank.add(" Banepa,Tel:+97711663535");
        Machapuchre_Bank.add(" Bharatpur Municipality-Sahid Chowk,Tel:+97756571271/571272 ");
        Machapuchre_Bank.add(" Nepal Rastraya Bank,Devkota Chowk,Biratnagar");
        Machapuchre_Bank.add(" Gajuri Bazar,Dhading,Tel:+97710402077/529218");
        Machapuchre_Bank.add(" Arhunge VDC-1, Campus Chowk, Beni Bazar");
        Machapuchre_Bank.add(" Lekhnath Chowk,Lekhnath-03,Kaski,Tel:+97761561717 ");
        Machapuchre_Bank.add(" Khairenitar,Tanahu ");
        Machapuchre_Bank.add(" Waling Mode,Waling");
        Machapuchre_Bank.add(" Branch,Chauraha Road,Dhandadi-4,Tel:+97791520556/520596");
        Machapuchre_Bank.add(" Laliguras Chowk,Baglung-3,Baglung Office Premises");
        Machapuchre_Bank.add(" Anbu Khaireni Chowk,Anbu Khaireni ");
        Machapuchre_Bank.add(" Rajbiraj Municipality,Ward-no-3,Neta Chowk,Opposite of District Development Committee");
        Machapuchre_Bank.add(" Mechi Rajmarg Chowk,Tel:+97724520526 ");
        Machapuchre_Bank.add(" Biratchowk ,Indrapur,Morang,Tel:021546230");
        Machapuchre_Bank.add(" Dhankuta ,Tel:+97726521437");
        Machapuchre_Bank.add(" Near Club Himalaya,Nagarkot ");
        Machapuchre_Bank.add(" Pokhara, Chipledhunga,Mahendrapul");
        Machapuchre_Bank.add(" Pokhara, Lakeside Branch Premises");
        Machapuchre_Bank.add(" Rambazar,Tel:+97761431193 ");
        Machapuchre_Bank.add(" Dhangadi NRB,Dhangadi");
        Machapuchre_Bank.add(" Chitwan Medical College,Chitwan");
        Machapuchre_Bank.add(" Lamachaur,Kaski");
        Machapuchre_Bank.add(" Umesh Marg,Ghorahi,Dang ");


        List<String> Janata_Bank = new ArrayList<String>();
        Janata_Bank.add("INSIDE KATHMANDU VALLEY");
        Janata_Bank.add(" Ason, Jyatha, Near Nepal Election Commission");
        Janata_Bank.add(" Balaju, Machhapokhari, Near Aryan Chowk");
        Janata_Bank.add(" Bhaktapur, Suryabinayak");
        Janata_Bank.add(" Chabil, Chuchchepati, K.L Tower");
        Janata_Bank.add(" Kalanki, Nayabazar ,Kirtipur");
        Janata_Bank.add(" Lalitpur, Kupondole-10, Area Of Sarvanga Nursing Home");
        Janata_Bank.add(" New Baneshwor, Near Oil Corporation, Sangam Marga");
        Janata_Bank.add(" New Road, Makhan, Adjecent to Suraj Arcade");
        Janata_Bank.add(" New Road, Ranjana Galli");
        Janata_Bank.add("OUTSIDE KATHMANDU VALLEY");
        Janata_Bank.add(" Achham, Mangalsen");
        Janata_Bank.add(" Biratnagar, Traffic Chowk");
        Janata_Bank.add(" Birgunj, Adarsa Nagar");
        Janata_Bank.add(" Butwal, Amarpath-08");
        Janata_Bank.add(" Darchula, Khalanga-5");
        Janata_Bank.add(" Dhangadi, Chauraha");
        Janata_Bank.add(" Itahari,");
        Janata_Bank.add(" Mahendranagar, Bhimdutta Muncipality-4, Kanchanpur");
        Janata_Bank.add(" Nepangunj, Surkhet Road");
        Janata_Bank.add(" Pokhara, New Road");
        Janata_Bank.add(" Rasuwa, Dhunche");
        Janata_Bank.add(" Rautahat, Gaur-1");
        Janata_Bank.add(" Rolpa, Liwang-06");
        Janata_Bank.add(" Sindhupalanchowk, Chautara");
        Janata_Bank.add(" Sunsari, Inaruwa");
        Janata_Bank.add(" Taplejung, Fungling Bazar");

        List<String> Kumari_Bank = new ArrayList<String>();
        Kumari_Bank.add("INSIDE KATHMANDU VALLEY");
        Kumari_Bank.add(" Balkhu Chowk Area");
        Kumari_Bank.add(" Budddhanilkantha. Narayanthan Milan Chowk");
        Kumari_Bank.add(" Chabahil, Chuchhepati");
        Kumari_Bank.add(" Durbarmargh, Opp of Nepal Investment Bank");
        Kumari_Bank.add(" Gongabu, Kantipur Mall");
        Kumari_Bank.add(" Kalanki Chowk, Millennium House");
        Kumari_Bank.add(" Koteshwor, Near Koteshwor Chowk");
        Kumari_Bank.add(" Lalitpur, Jhamsikhel, Opposite of St, Mary’s Bus Stop");
        Kumari_Bank.add(" Lalitpur, Kumaripati Area");
        Kumari_Bank.add(" Lazimpat, Big Mart Building(Way to Hotel Radission)");
        Kumari_Bank.add(" Naxal, Opposite Police Head Quater");
        Kumari_Bank.add(" New Baneshwor Chowk, Roal Thai Restaurant Premise");
        Kumari_Bank.add(" New Road, Near Rameshwor Sweets");
        Kumari_Bank.add(" Old Baneshwor, Near Banijya Bank");
        Kumari_Bank.add(" Patan Dhurbar Square(Near Honacha) ");
        Kumari_Bank.add(" Putalisadak, Ground Floor(Lobby)");
        Kumari_Bank.add(" Putalisadak, Right To Main Entrance Gate");
        Kumari_Bank.add(" Ratna Park, Nepal Electricity Authority Building");
        Kumari_Bank.add(" Thamel, Fire Club Building");
        Kumari_Bank.add("OUTSIDE KATHMANDU VALLEY");
        Kumari_Bank.add(" Baglung, Mahendra Path");
        Kumari_Bank.add(" Bhairahawa Branch, Narayan Path");
        Kumari_Bank.add(" Biratnagar, Morang Byapaar Sangh Building");
        Kumari_Bank.add(" Birgunj, National Medical College");
        Kumari_Bank.add(" Birgunj, Parsa, Adarsha Nagar");
        Kumari_Bank.add(" Butwal, Ram Mandir Line");
        Kumari_Bank.add(" Chitwan, Sauraha, Bacchauli-2");
        Kumari_Bank.add(" Damauli-2");
        Kumari_Bank.add(" Dang, Tulsipur, B.P Chowk");
        Kumari_Bank.add(" Itahari, Dharan Road, Pathivara Market");
        Kumari_Bank.add(" Jhapa, Birtamod");
        Kumari_Bank.add(" Kailali, Dhangadi, Ratopul");
        Kumari_Bank.add(" Kawasoti, Sabhapati Chowk");
        Kumari_Bank.add(" Morang, Urlabari");
        Kumari_Bank.add(" Narayangadh, Pulchowk");
        Kumari_Bank.add(" Nepalgunj, Dhamboji, Surkhet Road");
        Kumari_Bank.add(" Pokhara, Chiple Dhunga");
        Kumari_Bank.add(" Pokhara, Lakeside, Opposite to Lalupate Marga");
        Kumari_Bank.add(" Salyan, Khalanga");
        Kumari_Bank.add(" Surkhet, Birendra Nagar");


        List<String> Siddhartha_Bank= new ArrayList<String>();
        Siddhartha_Bank.add("INSIDE KATHMANDU VALLEY");
        Siddhartha_Bank.add(" Balkhu, Vayodha Hospital Premise");
        Siddhartha_Bank.add(" Banasthali, Siddhartha Banasthali Chowk");
        Siddhartha_Bank.add(" Bhaktapur, Manohara, BP Eye Foundation");
        Siddhartha_Bank.add(" Bouddha ");
        Siddhartha_Bank.add(" Budhanilkantha, Park Village");
        Siddhartha_Bank.add(" Chabahil Chowk, ATM Lounge");
        Siddhartha_Bank.add(" Dattatraya Durbar Square");
        Siddhartha_Bank.add(" Gatthaghar, Near Petrol Pump");
        Siddhartha_Bank.add(" Gongabu, Birendra Aishwarya Margh");
        Siddhartha_Bank.add(" Gwarko, B&B Hospital");
        Siddhartha_Bank.add(" Kalanki, Kalankisthan Road");
        Siddhartha_Bank.add(" Kamaladi, Hattrisar, Near Cima Building  ");
        Siddhartha_Bank.add(" Kumaripati, ATM Lounge");
        Siddhartha_Bank.add(" Maharajgunj, Bhairabnath Gan Premise");
        Siddhartha_Bank.add(" Maharajgunj");
        Siddhartha_Bank.add(" New Baneshwor, ATM Lounge");
        Siddhartha_Bank.add(" New Road, ATM Lounge, Dharma Path");
        Siddhartha_Bank.add(" Old Baneshwor, Kumari Complex");
        Siddhartha_Bank.add(" Patan, Patan Dhoka");
        Siddhartha_Bank.add(" Satdobato, Tikavairab Road");
        Siddhartha_Bank.add(" Sundarijal, Sundarijal Chowk, Bus Part");
        Siddhartha_Bank.add(" Sundhara, Civil Mall");
        Siddhartha_Bank.add(" Swayambhu, Halchowk");
        Siddhartha_Bank.add(" Thamel, ATM Lounge, Chaksibari Margh");
        Siddhartha_Bank.add(" Thamel, ATM Lounge, Thamel Narsing Chowk");
        Siddhartha_Bank.add(" Thamel, Mandala Street");
        Siddhartha_Bank.add(" Tinkune, Jagadamba Tower");
        Siddhartha_Bank.add("OUTSIDE KATHMANDU VALLEY");
        Siddhartha_Bank.add(" Bardibas");
        Siddhartha_Bank.add(" Bhairahawa, Prahari Tole");
        Siddhartha_Bank.add(" Biratnagar, Matrika Marg");
        Siddhartha_Bank.add(" Birgunj");
        Siddhartha_Bank.add(" Birtamode");
        Siddhartha_Bank.add(" Butwal, Hospital Line");
        Siddhartha_Bank.add(" Dailekh");
        Siddhartha_Bank.add(" Dang, Ghorahi");
        Siddhartha_Bank.add(" Dhangadi");
        Siddhartha_Bank.add(" Dharan");
        Siddhartha_Bank.add(" Hetauda, Bank Road");
        Siddhartha_Bank.add(" Itahari");
        Siddhartha_Bank.add(" Janakpur");
        Siddhartha_Bank.add(" Jhapa, Chandragadi");
        Siddhartha_Bank.add(" Jhapa, Damak");
        Siddhartha_Bank.add(" Kalaiya");
        Siddhartha_Bank.add(" Krishnanagar");
        Siddhartha_Bank.add(" Mahendranagar");
        Siddhartha_Bank.add(" Namche, Namche Bazar");
        Siddhartha_Bank.add(" Narayanghat");
        Siddhartha_Bank.add(" Nepalgunj");
        Siddhartha_Bank.add(" Pokhara Lounge, Halanchowk");
        Siddhartha_Bank.add(" Pokhara, Central Point, Lakeside");
        Siddhartha_Bank.add(" Pokhara, Lakeside");
        Siddhartha_Bank.add(" Pokhara, Srijana Chowk");
        Siddhartha_Bank.add(" Sindhuli");
        Siddhartha_Bank.add(" Sunauli, Hotel Mamata");
        Siddhartha_Bank.add(" Tikapur");
        Siddhartha_Bank.add(" Tulsipur");






        BankDetails.put("Everest Bank Ltd", Everest_Bank);
        BankDetails.put("Nepal Investment Bank Ltd", NIBL_Bank);
        BankDetails.put("Prabhu Bank Ltd", Prabhu_Bank);
        BankDetails.put("Standard Chartered Bank Ltd", Standard_Bank);
        BankDetails.put("Bank of Kathmandu", BOK_Bank);
        BankDetails.put("Nabil Bank Ltd", Nabil_Bank);
        BankDetails.put("Laxmi Bank Ltd", Laxmi_Bank);
        BankDetails.put("Rastriya Banijya Bank", RB_Bank);
        BankDetails.put("Nepal Bangladesh Bank Ltd",NB_Bank);
        BankDetails.put("Nepal SBI Bank Ltd",SBI_Bank);
        BankDetails.put("Himalayan Bank Ltd",Himalayan_Bank);
        BankDetails.put("Mega Bank Ltd",Megha_Bank);
        BankDetails.put("Global IME Bank Ltd",GlobalIME_Bank);
        BankDetails.put("Laxmi Bank Ltd",Laxmi_Bank);
        BankDetails.put("Kumari Bank Ltd",Kumari_Bank);
        BankDetails.put("Janata Bank Ltd",Janata_Bank);
        BankDetails.put("Machapuchre Bank Ltd",Machapuchre_Bank);
        BankDetails.put("Siddhartha Bank Ltd",Siddhartha_Bank);

        return BankDetails;

    }

}


